# Generated by Django 3.1.2 on 2021-02-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmasite', '0002_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='First_Name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Last_Name',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Subject',
            new_name='subject',
        ),
    ]
