# Generated by Django 3.1.2 on 2021-02-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmasite', '0003_auto_20210202_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='email',
            new_name='c_email',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='f_name',
            new_name='c_fname',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='l_name',
            new_name='c_lname',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='message',
            new_name='c_message',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='subject',
            new_name='c_subject',
        ),
    ]
